name: Deploy to GitHub Pages

on:
  push: # 移除 branches 限制
    paths:
      - '**' # 监听所有文件的更改

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build and export
        run: npm run export

      #   - name: Deploy to GitHub Pages
      #     uses: peaceiris/actions-gh-pages@v3
      #     with:
      #       github_token: ${{ secrets.GITHUB_TOKEN }}
      #       publish_dir: ./out
      #       destination_dir: blog
      - name: Conditional Deploy
        if: github.ref_name == 'main' || github.ref_name == 'master' || startsWith(github.ref_name, 'release/')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          destination_dir: blog
